Hw3
ArtemBerdnik/EPAM-Python-TestAutomation pull request #3
Opened 2022-10-13 18:08 UTC by ArtemBerdnik

All 4 tasks in HW3 are done. 
Tests pased

2022-10-13 19:09 UTC, alpakhomov requested changes
Посмотри плз hw3 еще раз.
Все остальное проверено.

2022-10-13 19:09 UTC, alpakhomov commented on HW3/hw3.py
> +def custom_range(seq: Sequence[str], end=-1, start=0, step=1) -> list:
В описании задания в начале дана выдержка из доки питона. Смысл такого кастомного range в том чтобы он следовал интерфейсу обычного range в питоне. Т.е. параметры всегда идут в определенном порядке (старт, стоп, степ). Передать их по ключу должно быть нельзя (иначе можно будет изменить порядок). Если бы функция всегда принимала все аргументы, ее сигнатура могла бы быть 
```python
def custom_range(seq, start, stop, step, /)
```
 так агрументы могут быть только позиционными. Но нужно еще предусмотреть варианты, когда передается только стоп, или (старт, стоп) и все это без возможности передавать keyword аргументы. 
Можно в test_hw3 добавить такой тест, он должен пройти на функции с правильной сигнатурой:
```python
import inspect


def test_positional_only_2():
    for _, kw in inspect.signature(custom_range).parameters.items():
        assert kw.default == inspect.Parameter.empty
```

2022-10-15 14:43 UTC, ArtemBerdnik commented on HW3/hw3.py
> +def custom_range(seq: Sequence[str], end=-1, start=0, step=1) -> list:
Спасибо. 
 Поправил

2022-10-15 16:15 UTC, alpakhomov approved these changes
Теперь все ок!

2022-10-15 16:31 UTC, merged